### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by TheHackGuy**
These translation updates are based on missing translations listed in[ this document.](https://squidly271.github.io/languageErrors.html#nl_NL) found in[ this post](https://forums.unraid.net/topic/94168-dutch-missing-translation-tracking/)

Personally my main language is Dutch, the translations should be correct.

I updated every missing translation in already existing files. 

The following files are added:
- /Unassigned Devices/editsettings.tx

The following files still need to be translated: (I will do this later, still unknown when exactly)
- /Dynamix Active Streams/activestreams.txt
- /Dynamix Auto Fan/fansettings.txt
- /Dynamix Cache Dirs/folderchacingsettings.txt
- /Dynamix Date Time/datetime.txt
- /Dynamix Day Night/daynightssettings.txt
- /Dynamix File Integrity/fileintegrity.txt
- /Dynamix File Integrity/integrity.txt
- /Dynamix Local Master/smb.txt
- /Dynamix S3 Sleep/sleepsettings.txt
- /Dynamix SSD Trim/scheduler.txt
- /Dynamix System Info/systemprofiler.txt
- /Dynamix System Stats/statsettings.txt
- /Dynamix System Stats/stats.txt
- /Dynamix System Temp/tempsettings.txt
- /Enhanced Log/enhancedsyslogsettings.txt
- /Enhanced Log/enhancedsyslog.txt
- /File Activity/fileactivity.txt
- /Hotplug USB/libvirthotplugusb.txt
- /Open Files/openfiles.txt
- /Parity Check Tuning/paritychecktuning.txt
- /Tips and Tweaks/tipsandtweaks.txt

### CODE REVIEW

**Comment by bergware** [comment]
This looks good. Thank you.
You need to make one correction in "settings.txt"

Cumulative parity check=Commulatieve partycontrole
becomes
Cumulative parity check=Commulatieve pariteitscontrole

**Comment by spencerjunraid** [comment]
Great- thanks @bergware. I will merge and make those corrections manually.

Thank you very much @TheHackGuy

**Comment by bergware** [comment]
@spencerjunraid There are a few other corrections, I will make the update for that, since you already merged the PR

**Comment by spencerjunraid** [comment]
Ok.

**Pull request merged**
