### PR TITLE
Rewritten main.txt

### PR DESCRIPTION
**Pull request by DyonR**
I've rewritten a lot of sentences and fixed a lot of errors.
Errors that I noticed the most both 'Cache' and 'Pool' were both called 'Groep', which is wrong. I've also decided to rename 'opslagsysteem' to 'array'. If someone is capable enough to use Unraid, I expect them to know some English terms.
Also used informal language (Use of 'je/jouw' instead of 'u/uw').
If you do not agree with how I worded certain things, feel free to discuss.
I'll do all other files later when I feel like it, but this took me more than two hours already.

### CODE REVIEW

**Comment by spencerjunraid** [comment]
Thank you very much @DyonR

**Comment by spencerjunraid** [comment]
@bergware - can you review and lmk if you agree?

**Comment by bergware** [comment]
Let me start with saying that there is no right or wrong in translations. A translation is written with a certain intention and interpretation in mind. And this is the case here, you clearly have a different view, which doesn't match my view.

In version 6.9 we do not talk any longer about "cache". The implementation has now the ability to create one or more pools of devices, and each pool can be given a user defined name. As a convenience the pool "cache" is maintained when it already exists. The original English text still has several references to "cache", but basically this is incorrect since it is a pool now (we probably need to adjust the English text to correct this).

A pool of devices is seen as a group of devices, and devices in this case are storage, The same is true for the array, it consists of storage devices.

The above means that terms like opslag, groepopslag and opslagsysteem are intentionally chosen to convey my interpretation. And I see no reason to change my interpretation. I know, as Dutch we have the ongoing _struggle_ to use either a good Dutch word or simply leave the English word. 

There are some useful suggestions in your proposal though, but as a whole this PR can not be accepted.

**Comment by DyonR** [comment]
If the language that translations must be based off are wrong by itself already, then it's hard to make a proper translation. Unraid should fix their 'base language' first then before asking for translations, or update it in a timely manner, for example the 'cache' translation, and still spelling Unraid as 'unRAID'. On that note, I also think the use of the term 'device' and 'disk' should be more streamlined, since devices in an array are always storage mediums, since 'device' is a bit too of a generic name, since, for example, a GPU is also a 'device'. But aside, since this is not related to the nl_NL translation anymore.    
  
As you can see in my PR, I personally think that the use of some English words would be better. For example the word 'opslagsysteem', since Unraid also doesn't call itself a 'storage array'/'storage system', other 'close languages' like pt_PT, es_ES, fr_FR, de_DE, sv_SE also call this 'array'. Therefore I think 'array' would be a fine word to use.  
Translating the word 'share' is also a hard one, since there isn't a good Dutch word for it in my opinion, it is kinda 'map', but it's also a 'gedeelde map' (hence share, from the English word shared), therefore I believe _share_ would be better.
  
I understand that there are different views on how translations should be done or interpreted, which is fine. However, since there are no others translating this or making suggestions, this means we are also limited to two visions on translations now.  
Since our views might be too different, I might just open issues with suggestions instead of making PR so we could discuss it there.  
 
 I will probably still make direct PR's for spelling and grammer mistakes.

**Comment by spencerjunraid** [comment]
Ok- are there any particular changes that you can both agree on? 

Otherwise, it might be best to open a thread in the forums about specific words/phrases and if agreed, then go to the trouble of doing a PR/merging. Just a thought. Thanks for the efforts! They are much appreciated.

**Comment by bergware** [comment]
_> If the language that translations must be based off are wrong by itself already_
It is just a few cache references which are off, everything else is fine. This will get corrected overtime though.

_> and still spelling Unraid as 'unRAID'_
I am pretty sure we have all replaced by Unraid, please point out where you see this

_> On that note, I also think the use of the term 'device' and 'disk' should be more streamlined_
These terms are used since the introduction in 2005, and left as is for product consistency. We should be very careful with changing these basics, but you can always make a feature request on the forum.

_> However, since there are no others translating this or making suggestions_
I am both developer and translator at the same time. I know pretty well the (my) intentions of the GUI and anything new. Of course people can disagree, but original and translation won't be really off here.

_> Obviously you can just take whatever you think is fine from this PR._
Probably the best way moving forward.

**Comment by bergware** [comment]
> Ok- are there any particular changes that you can both agree on?

I will take some of the proposed translations, and then close this PR.

**Comment by bergware** [comment]
In Dutch both new spelling "nivo" and old spelling "niveau" are perfectly legal, like "buro" and "bureau".
Though, I will change it to "niveau" as you suggest.

**Comment by DyonR** [comment]
Well no offense, but I can not find any references about the fact that 'nivo' or 'buro' is considered 'new' or 'correct' spelling in Dutch.  
My references:  
https://woordenlijst.org/#/?q=nivo  
https://onzetaal.nl/taaladvies/bureau-buro/  
https://taaladvies.net/taal/advies/vraag/153/buro_bureau_nivo_niveau_kado_cadeau/

**Comment by bergware** [comment]
See https://www.vandale.nl/gratis-woordenboek/nederlands/betekenis/nivo

The printed version of "van Dale" shows all alternative and official spellings.

**Comment by spencerjunraid** [comment]
OK. Is this ready to merge?

**Comment by bergware** [comment]
No, this PR II will close.
Instead other updates are made with several of the proposals in this PR.

**Pull request closed without merging**
