### PR TITLE
Update docker.txt

### PR DESCRIPTION
**Pull request by OmgImAlexis**
@bergware I noticed a few typos in just this repo I'm guessing we may have the same issue in others. How shall we go about this as the script breaks because of it.

### CODE REVIEW

**Comment by bergware** [comment]
Because we are not in a steady state yet, easiest is to make PRs and merge manually.

Surely hope these typos are exceptions. I have put a lot of attention to the files.

Thanks for spotting, I'll merge this one

**Comment by OmgImAlexis** [comment]
Seems most of them are missing `'` or `=` is replaced with `-`.

**Comment by bergware** [comment]
This is really odd, because I am pretty confident all files have (had) correct '=' signs.
The parser would have an issue, if this isn't the case.

Don't know if something got screwed!

**Comment by OmgImAlexis** [comment]
Seems that's the main thing that was breaking my sync tool. Once we get those issues fixed up it should run well again. :)

**Comment by bergware** [comment]
I guess you were also referring to a newline at the end?

That was on purpose, but I am going to add this in case the script has an issue with it.

**Comment by OmgImAlexis** [comment]
Ah yes the script adds a new line at the end but that shouldn't be an issue. I might have the script exclude whitespace changes before trying to push the new branch.

**Pull request merged**
